### ISSUE TITLE
[BUG] panic when multiple events are set in empty namespace

### ISSUE THREAD

**Issue by heliosgo** [kataras/neffos#102]
**Describe the bug**
When multiple events are set in empty namespace, and include `OnNativeMessage`, it may panic if received native message before `connectedNamespaces` is set.

**Screenshots**
![image](https://github.com/kataras/neffos/assets/103020869/a946ab1f-29e4-4655-8b98-a34869f41827)

Here is some source code I found. 
```golang
func (c *Conn) handleMessage(msg Message) error {
	if msg.isInvalid {
		return ErrInvalidPayload
	}

	if msg.IsNative && c.allowNativeMessages {
		ns := c.Namespace("")
		return ns.events.fireEvent(ns, msg)               // panic
	}

	......

	return nil
}
```

I think the code should be like this.
```golang
func (c *Conn) handleMessage(msg Message) error {
	if msg.isInvalid {
		return ErrInvalidPayload
	}

	if msg.IsNative && c.shouldHandleOnlyNativeMessages {    // this line
		ns := c.Namespace("")
		return ns.events.fireEvent(ns, msg)         
	}

	......

	return nil
}
```

**Comment by jiennyx** [comment]
pr https://github.com/kataras/neffos/pull/103
