### ISSUE TITLE
How do I get a list of connected users in a room?

### ISSUE THREAD

**Issue by EhsaanIqbal** [kataras/neffos#14]

**Comment by kataras** [comment]
Hello @EhsaanIqbal, neffos does not give you a list of connections per room. But it's quite easy to do it by yourself, depends on your needs. For example, you have a **mutex and a map** of `map[string][]neffos.Conn` or `neffos.NSConn`, key is the room name and value is a list of connections. Neffos has the `neffos.OnRoomJoined` event which you can use to take actions when a connections joins to a room. In that event's callback you can `append` the connection to the specific room's list.
