### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nearcode** [kataras/neffos#35]
**Describe the bug**
Call GetConnectionsByNamespace appeared abnormal

> Note, if that bugs is a browser relative please report it at the [neffos.js](https://github.com/kataras/neffos.js) repository instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/13174362/77043020-ae47c880-69f7-11ea-882e-3f0acf608cee.png)
![image](https://user-images.githubusercontent.com/13174362/77042485-af2c2a80-69f6-11ea-9880-03cb8f32fd89.png)
![image](https://user-images.githubusercontent.com/13174362/77042346-7e4bf580-69f6-11ea-9ae7-6954529a18a3.png)

**Desktop (please complete the following information):**
 - OS: UBUNTU
 - Version 18.04.02

**Comment by kataras** [comment]
Hello @nearcode, this is **not a bug**. The `GetConnectionsByNamespace` is documented as **Not thread safe**, that means that you have to use mutex locks by your own whenever you need concurrent access (it's up to you). Read its documentation below, thanks!

https://github.com/kataras/neffos/blob/a6bf2abffa382d9722f7d300713371da86f4ed47/server.go#L571-L577
