### ISSUE TITLE
[BUG] the neffos server hang up whole goroutines

### ISSUE THREAD

**Issue by LeeEirc** [kataras/neffos#37]
**Describe the bug**
After upgrade lastest version, it still happened on productions. Debugging by dlv tool, I found the neffos block whole process.

**Screenshots**
![4011585729190_ pic_hd](https://user-images.githubusercontent.com/32626707/78118258-579baf00-7439-11ea-8730-c2e712a69ca7.jpg)
![4021585729215_ pic_hd](https://user-images.githubusercontent.com/32626707/78118264-59fe0900-7439-11ea-98c2-897637b0d763.jpg)

**Desktop (please complete the following information):**
 - OS: Centos
 - Version 7.7

Could you have time to handle this questions?

**Comment by LeeEirc** [comment]
this is our project. [koko](https://github.com/jumpserver/koko. )

**Comment by kataras** [comment]
@LeeEirc will take a look of it soon, please stay tuned.

**Comment by LeeEirc** [comment]
@kataras I do not think it is the root cause at current, as we do not use `Room` in our project. I think the process hang up  by using atomic package. Is there any tools or ways to help me solve it?

**Comment by kataras** [comment]
It is because of Broadcast, if you enable redis or nats stackexhange you will see huge difference and that hanting will be disappear especially running multiple neffos servers as one

**Comment by LeeEirc** [comment]
I'm not convinced that the stackexhange could solve the problem. I think every single neffos server should work well. I am not sure whether I misuse the neffos package.

**Comment by LeeEirc** [comment]
```
sshWs.OnConnect = func(c *neffos.Conn) error {
		if c.WasReconnected() {
			namespace := c.Socket().Request().Header.Get("X-Namespace")
			if namespace != "" {
				_, _ = c.Connect(context.TODO(), "ssh")
			}
		} else {
			logger.Debug("A new ws connection arrive")
		}
		return nil
	}
```
This is our code snippet about handling reconnected connection.  I think the `Connect`  cause the  hang problem. Now I remove these codes.

**Comment by kataras** [comment]
Hello @LeeEirc, if the connect is hanging then there is an issue on https://github.com/kataras/neffos/blob/a6bf2abffa382d9722f7d300713371da86f4ed47/process.go#L59 which does use the atomic package. However, in the second log of yours, I see the `broadcaster.waitUntilClosed` and that's is used on `Broadcast` if no stackexchange is used. 

> I think every single neffos server should work well.

Yes you are correct, [stackexchanges](https://github.com/kataras/neffos/wiki/Scale-out) do work with a single server as well and it's a way to move/log the messages on platforms like kafka too.

I will spend my rest of my free time to fix your issue, as it's the only blocker for the next Iris release (v12.2.0).

**Comment by kataras** [comment]
Hello @LeeEirc, if the connect is hanging then there is an issue on https://github.com/kataras/neffos/blob/a6bf2abffa382d9722f7d300713371da86f4ed47/process.go#L59 which does use the atomic package. However, in the second log of yours, I see the `broadcaster.waitUntilClosed` and that's is used on `Broadcast` if no stackexchange is used. 

> I think every single neffos server should work well.

Yes you are correct, [stackexchanges](https://github.com/kataras/neffos/wiki/Scale-out) do work with a single server as well and it's a way to move/log the messages on platforms like kafka too.

I will spend the rest of my free time to fix that issue, as it's the only blocker for the next Iris release (v12.2.0). My only difficulty here is that **I dont have a reproducible example, the koko repository you posted above, contains a lot of code that many of that wraps the neffos features and I can't debug each one of them, if you give me an example that produces the same error I can fix it very fast**

**Comment by kataras** [comment]
@LeeEirc did you try to set `SyncBroadcaster` neffos server's field to true?

**Comment by kataras** [comment]
Hello @LeeEirc, if it was a problem caused by latest version and it has to do with the `Connect` then it should be fixed now. Could you please fetch the latest neffos from master and confirm that the patch actually fixed the issue so we can tag a new release? Thanks in advance!

`go get github.com/kataras/neffos@master` from inside your `go.mod` project.

**Comment by jjhesk** [comment]
i have the same problem as well.
