### ISSUE TITLE
[question] Why brower loop print re-connected and send head endpoint request?

### ISSUE THREAD

**Issue by 23233** [kataras/neffos#42]
### I'm use neffos.js code :
![image](https://user-images.githubusercontent.com/12870070/82308675-b40c5b00-99f4-11ea-9b94-e6f93dc0d050.png)

#### But i'm find console loop print re-connected , time is i'm set reconnect , This is keeplive?

![image](https://user-images.githubusercontent.com/12870070/82308593-917a4200-99f4-11ea-8d4e-a83b0855366f.png)

#### And find console print send HEAD methods to set endpoint , I'm set iris to Any but is not work 
![image](https://user-images.githubusercontent.com/12870070/82308879-fc2b7d80-99f4-11ea-81fe-9f84f856df4d.png)

**Comment by kataras** [comment]
@23233 There is nothing wrong with neffos for that, probably you have a middleware that responds with `StatusForbidden (403)`. Can you post a server-side code snippet that can re-produce this issue please?

**Comment by 23233** [comment]
@kataras  Yes, thanks this is my probile , fix it ~
