### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by nearcode** [kataras/neffos#54]
fatal error: concurrent map iteration and map write

goroutine 46 [running]:
runtime.throw(0x1842c28, 0x26)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc002fd9bf8 sp=0xc002fd9bc8 pc=0x433a62
runtime.mapiternext(0xc002fd9cd0)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/map.go:853 +0x552 fp=0xc002fd9c78 sp=0xc002fd9bf8 pc=0x40f5e2
runtime.mapiterinit(0x1603200, 0xc000e9bf80, 0xc002fd9cd0)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/map.go:843 +0x1c4 fp=0xc002fd9c98 sp=0xc002fd9c78 pc=0x40ef94
github.com/kataras/neffos.(*Server).GetConnections(0xc0008c6700, 0x0)
	/Users/near/go/pkg/mod/github.com/kataras/neffos@v0.0.18/server.go:606 +0x9b fp=0xc002fd9d40 sp=0xc002fd9c98 pc=0x10b8b6b

**Comment by kataras** [comment]
@nearcode Please read the godocs before using a method. That method is NOT safe for concurrent use:

https://github.com/kataras/neffos/blob/2221a9afc8392b9a3e984473dd34f8380ce80840/server.go#L601-L602

Use `Mutex` to lock your callers instead.
