### ISSUE TITLE
[FEATURE REQUEST] Rooms Authentication

### ISSUE THREAD

**Issue by bigBron** [kataras/neffos#7]
The client-side JoinRoom method cannot pass metadata to the server-side for authenticating.
for now, the rooms are accessible to all users, but in some situations, we need only allow specific users to join some rooms.

**Comment by kataras** [comment]
The `JoinRoom`, as any other event, can be authenticated by the server-side. If the returned error from server is not nil, then it dissalows client to emit an event/ or join to a room in this case and return that error instead.

```go
neffos.OnRoomJoin = func(c *neffos.NSConn, msg neffos.Message) error {
    httpReq:= c.Socket().Request()
    // [...validate]
    return errors.New("you cannot access this room")
}
```

You need metadata for authentication outside of the initialize `Request`? In your case a user can be valid after some time by itself without server ack?

**Comment by bigBron** [comment]
I'm sorry to reply so late. Now I use `conn#socket().Request()` to get metadata for authenticating, which can work very well.
